trigger:
  branches:
    include:
      - main  # or 'master' depending on your repo

pool:
  name: 'Default'

steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Running pipeline..."
      Get-Content yourfile.txt  # Replace with your actual file
