trigger:
  branches:
    include:
      - main  # or 'master' depending on your repo

pool:
  name: 'Default'

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Running pipeline..."
      cat yourfile.txt  # change to the file you want to import/process
